name: Publish Wasm Plugin

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust and target
        run: |
          rustup target add wasm32-wasip1
          cargo build --release --target wasm32-wasip1

      - name: Install ORAS
        uses: oras-project/setup-oras@v1
        with:
          version: 1.2.2

      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Wasm Plugin with Metadata
        run: |
          oras push ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} \
            target/wasm32-wasip1/release/plugin.wasm \
            --artifact-type application/vnd.module.wasm.content.layer.v1+wasm \
            --annotation org.opencontainers.image.title="Ark MCP Test Time plugin" \
            --annotation org.opencontainers.image.description="WASM test plugin for Ark MCP server" \
            --annotation org.opencontainers.image.version="${{ github.event.release.tag_name }}" \
            --annotation org.opencontainers.image.authors="vpopescu" \
            --annotation org.opencontainers.image.licenses="MIT" \
            --annotation org.opencontainers.image.source="https://github.com/${{ github.repository }}" \
            --annotation org.opencontainers.image.documentation="https://github.com/${{ github.repository }}/blob/main/README.md" \
            --annotation org.opencontainers.image.url="https://github.com/${{ github.repository }}" \
            --annotation org.opencontainers.image.created="$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            --annotation org.opencontainers.image.revision="${{ github.sha }}" \
            --annotation org.opencontainers.image.vendor="Ark MCP"
            